Add better check for directory

diff --git a/.github/workflows/publish-coverage.yml b/.github/workflows/publish-coverage.yml
--- a/.github/workflows/publish-coverage.yml
+++ b/.github/workflows/publish-coverage.yml
@@ -35,8 +35,14 @@ jobs:
 
       - name: Check contents of coverage_html
         run: |
-          ls -l coverage_html || echo "Folder missing"
-          [ -f coverage_html/index.html ] && echo "✅ Found index.html" || (echo "❌ No index.html" && exit 1)
+          if [ -d coverage_html ]; then
+            echo "✅ coverage_html folder found. Contents:"
+            ls -l coverage_html
+          else
+            echo "❌ coverage_html folder is missing!"
+            exit 1
+          fi
+          [ -f coverage_html/index.html ] && echo "✅ Found coverage_html/index.html" || (echo "❌ No index.htmln in coverage_html folder" && exit 1)
         
       - name: Deploy coverage to gh-pages branch
         uses: peaceiris/actions-gh-pages@v4
